### ISSUE TITLE
Fedora Silverblue - Auto detect doesn't work, app closes

### ISSUE THREAD

**Issue by sebasmonia** [iongion/podman-desktop-companion#28] opened 2022-04-12 14:58 UTC
The app looks great from the screenshots!

It does have a problem running it in Fedora Silverblue, after I "Save" on container environment = Native, the window closes and nothing else happens.
This is with the AppImage version.

**Comment by iongion** [comment] 2022-04-12 15:11
Thank you for the kind words.

I need more tests though from users to have it reach stability. That save should set the engine to `native` and restart the app. Maybe appImage is not so restart friendly.

According to this, the preferences are saved in

https://github.com/megahertz/electron-cfg/blob/master/src/utils.js#L90 

As far as I read, SilverBlue is doing some immutability, maybe this impacts the ways settings are saved/loaded.
I will install a VM with it and test.

**Comment by sebasmonia** [comment] 2022-04-12 15:35
I see the settings in `~/.config/podman-desktop-companion/electron-cfg.json`, and they are set to `native`, but when I launch the app again the same screen shows up.
As if the settings were never saved. Maybe it is reading them from another location.

For a coworker on OS X it doesn't detect podman machine correctly.

**Comment by iongion** [comment] 2022-04-13 13:07
Just released a new version for all OSs - https://github.com/iongion/podman-desktop-companion/releases/tag/4.0.3-b.2

Either it solves the issue or you will be able to get more information from the logs - added as much debugging possibilities as possible.

![image](https://user-images.githubusercontent.com/867609/163186611-32111e9f-c70b-47bd-a907-3e5844ea7724.png)

**Comment by sebasmonia** [comment] 2022-04-13 13:47
Thank you for the quick turnaround! It is working now.

It does say there are 17 containers running, but if you go to "containers" there's just one running and the rest are `exited`/`created`.

And the "images" section hangs forever.

PS: The app is super pretty

**Comment by iongion** [comment] 2022-04-13 14:25
That is so good to hear and thank you so much for the appreciation.

The counter is indeed misleading - it counts all and does not apply the `running` filter indeed, will address it on an upcoming release.

For the `images` hanging - if you have time, could you try to activate the `debug` log and check the logs, it is a `GET` on `/images/json` - the debug will generate a curl command line that you could simply paste in the terminal and see the effects.

**Comment by sebasmonia** [comment] 2022-04-13 14:41
No /images/json URL, the only curl calls I see in the log directory are these these:
```
-*- mode: grep; default-directory: "~/.config/podman-desktop-companion/logs/" -*-
Grep started at Wed Apr 13 08:36:11

[find/grep removed for brevity]

./worker.log1113:[2022-04-13 08:29:39.316] [debug] [container-client] HTTP request curl -v -X GET --unix-socket "/tmp/podman-desktop-companion-podman-rest-api.sock" "http://d/v3.0.0/libpod/_ping" -H "Accept: application/json" -H "Content-Type: application/json"
./worker.log1142:[2022-04-13 08:29:39.587] [debug] [container-client] HTTP request curl -v -X GET --unix-socket "/tmp/podman-desktop-companion-podman-rest-api.sock" "http://d/v3.0.0/libpod/_ping" -H "Accept: application/json" -H "Content-Type: application/json"
./worker.log1146:[2022-04-13 08:29:40.598] [debug] [container-client] HTTP request curl -v -X GET --unix-socket "/tmp/podman-desktop-companion-podman-rest-api.sock" "http://d/v3.0.0/libpod/_ping" -H "Accept: application/json" -H "Content-Type: application/json"
./worker.log1150:[2022-04-13 08:29:40.618] [debug] [container-client] HTTP request curl -v -X GET --unix-socket "/tmp/podman-desktop-companion-podman-rest-api.sock" "http://d/v3.0.0/libpod/_ping" -H "Accept: application/json" -H "Content-Type: application/json"
./worker.log1154:[2022-04-13 08:29:40.625] [debug] [container-client] HTTP request curl -v -X GET --unix-socket "/tmp/podman-desktop-companion-podman-rest-api.sock" "http://d/v3.0.0/libpod/info" -H "Accept: application/json" -H "Content-Type: application/json"
./worker.log1157:[2022-04-13 08:29:40.679] [debug] [container-client] HTTP request curl -v -X GET --unix-socket "/tmp/podman-desktop-companion-podman-rest-api.sock" "http://d/v3.0.0/libpod/_ping" -H "Accept: application/json" -H "Content-Type: application/json"

Grep finished with 6 matches found at Wed Apr 13 08:36:11
```

**Comment by sebasmonia** [comment] 2022-04-13 16:13
The curl command:
`curl -v -X GET --unix-socket "/tmp/podman-desktop-companion-podman-rest-api.sock" "http://d/v3.0.0/libpod/images/json" -H "Accept: application/json" -H "Content-Type: application/json"`
Returns after about 3 minutes, even `podman images` on the terminal takes up to a minute to complete, so this is definitely not on you. The window does disable and becomes unresponsive, probably because curl times out or something like that.

**Comment by iongion** [comment] 2022-05-15 20:44
Closing this for now, feel free to reopen if needed, if you find out why is getting stuck from time to time, I am very interested, sometimes I experience it myself, but I am unable to reproduce or find anything about it.

In the last release I added even more verbosity to the logs in what concerns podman's own log, try to see if it can help us all.

**Closed by iongion** 2022-05-15 20:44 UTC
